### ISSUE TITLE
Validar a acessibilidade do site da FACOM.

### ISSUE THREAD

**Issue by viniEng** [fujinoharaufms/GCS_Amigues#10]
Tendo em vista o intuito de aprimorar o site da FACOM, com o finco de corrigir problemas de acessibilidade. Creio ser preciso o uso de uma ferramenta de depuração do _site,_, para poder analisar o site como um todo e documentar quais melhorias precisam ser feitas e onde, com o máximo de detalhes possível. 

Para tanto gostaria de pensar com vocês qual ferramenta poderia ser usada, e como poderíamos nos organizar frente a este objetivo.

**Comment by Rai-anjos** [comment]
Olha eu sugiro que você use essa ferramenta aqui: https://wave.webaim.org/ é online e, é só colocar a URL para a acessibilidade do site ser avaliada. E também podemos fazer um roadmap do site e dividir em partes as análises.
