### ISSUE TITLE
Front-end da página de eventos e informações sobre antigos eventos

### ISSUE THREAD

**Issue by Rai-anjos** [fujinoharaufms/GCS_Amigues#16]
Preciso de ajuda para fazer toda a programação de front-end da página eventos, e ver como ficariam melhor os pop-ups(se está tendo evento ou não). E também temos que ver se temos informações dos antigos eventos para já deixar postado.

**Comment by viniEng** [comment]
@Rai-anjos, acredito que o primeiro passo seja fazer o protótipo e, quanto a isso acredito ser sua especialidade, mas podemos alinhar melhor. Quanto a ver se temos informações dos antigos eventos, acredito que seja necessário uma reunião, para analisar a quem recorreríamos para isso.
