### ISSUE TITLE
Problema de responsividade na seção "Destaques" da página inicial.

### ISSUE THREAD

**Issue by Pedro-Varela** [fujinoharaufms/GCS_Amigues#17]
Na página inicial do site da Faculdade de Computação da UFMS, a seção "Destaques" apresenta um problema de alinhamento visual dos ícones (conforme a figura). Enquanto a primeira linha de ícones está alinhada corretamente, a segunda linha diverge dessa estrutura, criando uma discrepância que compromete a estética do site e pode levar à confusão sobre a organização do conteúdo por parte dos usuários.

![image](https://github.com/fujinoharaufms/GCS_Amigues/assets/64024622/c55c7cbd-1923-4a59-bbcb-24ab07d3db02)

Ajustar os ícones da segunda linha para que sigam o mesmo alinhamento e espaçamento da primeira linha, mantendo uma consistência visual em toda a seção. Isso pode ser realizado ajustando o CSS responsável pela disposição dos elementos. Um teste de responsividade em diferentes dispositivos com telas diferentes também é recomendado para garantir que a alteração mantenha o alinhamento em todas as resoluções de tela.

**Comment by Rai-anjos** [comment]
Acredito que tem apenas div em formas de colunas e esse é o problema, que o ícone que vem embaixo está apoiado no ícone acima e por isso o problema. Se criarmos uma linha na horizontal ele vai se apoiar no ícone acima "mais longo" e acredito que o problema será resolvido.
