### ISSUE TITLE
Página de Financiadores confusa

### ISSUE THREAD

**Issue by fujinoharaufms** [fujinoharaufms/GCS_Amigues#2]
Ao navegar pelos links da página principal, reparei que a página de financiadores (/ppgcc/financiadores) está confusa e com uma estética precária: partes em inglês, imagens desorganizadas e asteriscos que não fazem referência a nada na imagem. Precisamos, pelo menos deixá-la em português - para o tradutor automático lidar com a tradução caso algum usuário selecione outra língua -, usar um padrão simples para o posicionamento e tamanho das imagens e remover os asteriscos desnecessários. Acho que os conhecimentos de UX da Raissa vão lidar bem com este problema. É possível melhorar mais a estética da página, porém esses pontos são mais importantes no momento.

**Comment by Rai-anjos** [comment]
Como o site base é em inglês, pode ser que algumas palavras não tenham sido traduzidas. Já em questão de estética não sei se posso mudar muito, mas vou ver o que da para fazer e não sair muito do padrão do site como um todo.
