### ISSUE TITLE
Desenvolvimento e Preenchimento da Página de Eventos

### ISSUE THREAD

**Issue by Pedro-Varela** [fujinoharaufms/GCS_Amigues#20]
Esta issue é um complemento à issue #16, que identificou a falta de funcionalidade no botão "Eventos".

O botão "Eventos", que deveria levar a uma página com informações sobre atividades futuras, atualmente não conduz a uma página existente. Esta situação, agora requer atenção especial para que seja desenvolvida uma solução que não apenas resolva o problema técnico, mas também preencha o espaço com conteúdo relevante e atualizado, enriquecendo assim a experiência do usuário no site.

Estamos em busca de colaboradores para assumir a responsabilidade de reunir informações sobre eventos futuros e desenvolver a página de "Eventos". A tarefa envolve colaborar com os organizadores de eventos internos para garantir um fluxo contínuo de informações atualizadas.

**Comment by Lucashokama** [comment]
Creio que ao verificar a causa desse defeito, seria interessante já aproveitar para implementar a opção de selecionar Eventos Encerrados, Eventos em andamento e Eventos Futuros ao colocar o mouse em cima da opção de Evento, desse modo funcionaria da mesma maneira que as outras opções desse menu que ele está incluso. Melhorando assim a navegabilidade e a experiência do usuário ao mesmo tempo em que se conserta esse defeito.
