### ISSUE TITLE
Site fora do ar

### ISSUE THREAD

**Issue by fujinoharaufms** [fujinoharaufms/GCS_Amigues#3]
O site, frequentemente, fica fora do ar. Isso é mais problemático nos finais de semana, em que temos falta de técnicos para resolver isso e temos uma grande quantidade de acessos de alunos (entregas de atividades nos domingos). Precisamos procurar formas de backup para o site ser mais estável e checar se os servidores estão ficando sobrecarregados com quantidade de acessos. Não podemos descartar a possibilidade de ataques de DDoS, creio que seja importante fazermos uma revisão em nossos padrões de segurança para, pelo menos, evitar esses ataques no futuro.

**Comment by viniEng** [comment]
@fujinoharaufms Realmente, a indisponibilidade é um problema que temos enfrentado com frequência. Acredito que o próximo passo seja uma reunião com o pessoal de Infraestrutura, afim de entender os fatores basilares dessa problemática, assim como ações para mitigar a indisponibilidade.
