### ISSUE TITLE
Possível melhoria na qualidade de exposição das notícias no site principal.

### ISSUE THREAD

**Issue by Lucashokama** [fujinoharaufms/GCS_Amigues#9]
Após observar as notícias, tive um problema com poluição visual devido a grande quantidade de notícias exibidas simultaneamente, então acho que seria interessante adicionar um filtro de organização para dispor as informações de acordo com a opção escolhida nele, mas não sei ao certo como implementá-lo, alguém tem alguma ideia do quão possível é essa ideia dado os nossos recursos disponíveis?
![FourthIssue](https://github.com/fujinoharaufms/GCS_Amigues/assets/112421011/a6c3c71b-2232-4c79-9d8a-841af389d55f)

**Comment by fujinoharaufms** [comment]
Eu e Vinicius estamos estudando o Bootstrap, la tem uma função interessante que talvez resolva este problema.

**Comment by viniEng** [comment]
Acredito que esse tutorial seja útil: https://www.mxcursos.com/blog/jquery-filtrando-itens-de-uma-lista/

Basicamente, utiliza do Jquery para filtrar os elementos da lista, é o que o @fujinoharaufms comentou que o Bootstrap utiliza.
